In [67]:
import gymnasium as gym
import numpy as np
from gymnasium import logger, spaces

In [12]:
single_observation_space = spaces.Box(low=np.array([-1.0, -2.0, -1.0, -2.0]), high=np.array([2.0, 4.0, 3.0, 4.0]), dtype=np.float32)
print(single_observation_space.shape)

print(np.array(single_observation_space.shape).prod())


single_observation_space = spaces.Box(low=-1.0, high=2.0, shape=(3, 4), dtype=np.float32)
print(single_observation_space.shape)

print(np.array(single_observation_space.shape).prod())


(4,)
4
(3, 4)
12


In [95]:
b_inds = np.arange(10)
print(b_inds)

[0 1 2 3 4 5 6 7 8 9]


In [71]:
class testVecEnv(gym.vector.VectorEnv):
    def __init__(self, num_envs):
        state = self.np_random.uniform(
                    low=0, high=3, size=(4, num_envs)
                ).astype(np.float32)
        print(state)
        print(state.T)

testENv = testVecEnv(6)


[[1.218801   1.5734607  1.9244717  1.7615107  1.7921698  0.30776575]
 [0.3802162  1.7118129  0.7561735  1.8882654  1.6763033  0.05508927]
 [2.4410474  1.9189606  2.620124   2.8012583  2.4038153  1.5757871 ]
 [1.5236443  1.5643775  1.9509047  2.759129   0.04334366 1.8953404 ]]
[[1.218801   0.3802162  2.4410474  1.5236443 ]
 [1.5734607  1.7118129  1.9189606  1.5643775 ]
 [1.9244717  0.7561735  2.620124   1.9509047 ]
 [1.7615107  1.8882654  2.8012583  2.759129  ]
 [1.7921698  1.6763033  2.4038153  0.04334366]
 [0.30776575 0.05508927 1.5757871  1.8953404 ]]
<class '__main__.testVecEnv'>


In [66]:
tt = (5<2|5<3)
print(tt)
print(np.ones_like(tt,dtype=np.float32))

False
1.0
