In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.distributions import Categorical, Normal



In [17]:
probs = Normal(0.0, 0.2)
log_probs = probs.log_prob(torch.Tensor([0.0]))
prob = probs.cdf(torch.Tensor([0.0]))
print(log_probs)
print(torch.exp(log_probs))
print(prob)
print(probs.sample())

tensor([0.6905])
tensor([1.9947])
tensor([0.5000])
tensor(-0.0610)
