In [2]:
import torch
import torch.nn as nn

In [4]:
cc = torch.tensor([True, True, False, False])

In [146]:
dones = torch.zeros((6, 4))
next_done = torch.tensor([True, True, False, False])
next_done = next_done.to(torch.int)
print(next_done)

tensor([1, 1, 0, 0], dtype=torch.int32)


In [19]:
print(w)
print(w[:,1])
cc = torch.dot(w[:,0].T, w[:,1].T)
print(cc)

print(torch.matmul(w, w.t()))

tensor([[-0.6487, -0.0209,  0.7608],
        [ 0.5225,  0.7146,  0.4651],
        [-0.5533,  0.6992, -0.4526]])
tensor([-0.0209,  0.7146,  0.6992])
tensor(0.)
tensor([[ 1.0000e+00, -2.9802e-08,  2.9802e-08],
        [-2.9802e-08,  1.0000e+00, -4.4703e-08],
        [ 2.9802e-08, -4.4703e-08,  1.0000e+00]])


torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)  
$y = xA^T+B$
Variabels:
- weight(torch.Tensor): shape(out_feature, in_feature)
- bias: shape(out_feature)

example:
```python
m = nn.Linear(20,30)
print(m.weight.shape)
```
will give (30, 20)
So [1x30] = [1*20] *[20 * 30] + [30 *1]  
$A^T$ is [20 *30]  
A therefore is [30 * 20]  
The orthogonal_ make this matrix $A^TA=I$  
The gain in the orthogonal_ is multiplied to each element 

In [32]:
m = nn.Linear(20,1)
input = torch.randn(20)
output = m(input)
print(m.weight.shape)

torch.Size([1, 20])


In [81]:
model = nn.Linear(1, 1)

print(model.weight.size())
print(model.weight)
print(model.bias)
loss_function = nn.MSELoss()

torch.Size([1, 1])
Parameter containing:
tensor([[0.9205]], requires_grad=True)
Parameter containing:
tensor([-0.0694], requires_grad=True)


In [84]:
# optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
inputs = torch.tensor([[1.0], [2.0], [3.0], [4.0]], requires_grad=True)
# targets = torch.tensor([[2.0], [4.0], [6.0], [8.0]])
predictions = model(inputs)
print(predictions)

model.zero_grad()
predictions.backward(torch.ones_like(predictions))

print(model.weight)
print(model.weight.grad)
print(inputs.grad)
# loss = loss_function(predictions, inputs)
# print(loss)


tensor([[0.8510],
        [1.7715],
        [2.6920],
        [3.6124]], grad_fn=<AddmmBackward0>)
Parameter containing:
tensor([[0.9205]], requires_grad=True)
tensor([[10.]])
tensor([[0.9205],
        [0.9205],
        [0.9205],
        [0.9205]])
